apiVersion: v2
name: vault-deployment
description: HashiCorp Vault deployment for storing MinIO credentials
type: application
version: 1.0.0
appVersion: "1.18.2"

dependencies:
  - name: vault
    version: 0.29.1
    repository: https://helm.releases.hashicorp.com
